DELETE http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "Content": "This is a note",
}

###
//Fallos
POST http://localhost:3001/api/notes

